language : python
python:
    - "3.6"

install:
  - pip install -r requirements.txt

env:
  - FLASK_VERSION=1.0.2

script: 
   - nosetests --exe --with-coverage --cover-package=app

after_script:
  - coveralls
